baseURL = "https://rootkiddie.com/"
languageCode = "en-us"
title = "Welcome - RK"

hasCJKLanguage = "true"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

theme = "hello-programmer"
paginate = 5

[taxonomies]
    tag = "tags"
    category = "categories"

googleAnalytics = "UA-XXXXXXXX-X"

[author]
    name = "Li Bailin"
    homepage = "https://rootkiddie.com"

